version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: $DBHOST
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: $DBPASSWD
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
